flowchart TD
N6("AZ 1")
N2("Region 2")
N1(" ")
N4("AZ 1")
N5("AZ 1")
N7("AZ 1")
N0(" ")
N3("AZ 1")
N3 --> N1 --> N7
N5 --> N2 --> N6
style N6 stroke:#1e1e1e,fill:transparent;
style N2 stroke:#1e1e1e,fill:transparent;
style N1 stroke:#1e1e1e,fill:transparent;
style N4 stroke:#1e1e1e,fill:transparent;
style N5 stroke:#1e1e1e,fill:transparent;
style N7 stroke:#1e1e1e,fill:transparent;
style N0 stroke:#1e1e1e,fill:transparent;
style N3 stroke:#1e1e1e,fill:transparent;
